export enum ErrorCode {
    // 400
    BAD_REQUEST = 'BAD_REQUEST',
    BAD_CONTENT = 'BAD_CONTENT',
    KEY_EXPIRED = 'KEY_EXPIRED',
    KEY_INVALID = 'KEY_INVALID',
    INPUT_INVALID = 'INPUT_INVALID',
    IP_INVALID = 'IP_INVALID',
    UUID_INVALID = 'UUID_INVALID',

    USER_ALREADY_VOTED = 'USER_ALREADY_VOTED',
    EXISTING_THIRD_PARTY_ACCOUNT = 'EXISTING_THIRD_PARTY_ACCOUNT',
    PASSWORD_NOT_UPDATED = 'PASSWORD_NOT_UPDATED',
    BRAND_WIDGET_IDS_INVALID = 'BRAND_WIDGET_IDS_INVALID',
    BRAND_CANNOT_USE_OVER_ONE_TEMPLATE = 'BRAND_CANNOT_USE_OVER_ONE_TEMPLATE',
    IMAGE_URL_CANNOT_BE_BLANK = 'IMAGE_URL_CANNOT_BE_BLANK',
    FILE_DOES_NOT_MATCH = 'FILE_DOES_NOT_MATCH',
    MISSING_BACKGROUND_TYPE = 'MISSING_BACKGROUND_TYPE',
    INDEX_MUST_BE_LESS_THAN_ARRAY_LENGTH = 'INDEX_MUST_BE_LESS_THAN_ARRAY_LENGTH',

    // 401
    UNAUTHORIZED = 'UNAUTHORIZED',
    AUTH_REQUIRED = 'AUTH_REQUIRED',
    AUTH_ERROR = 'AUTH_ERROR',
    SESSION_EXPIRED = 'SESSION_EXPIRED',
    AUTH_INCORRECT_PASSWORD = 'AUTH_INCORRECT_PASSWORD',
    AUTH_EMAIL_NOT_FOUND = 'AUTH_EMAIL_NOT_FOUND',

    // 402
    PAYMENT_REQUIRED = 'PAYMENT_REQUIRED',
    DAILY_LIMIT_EXCEEDED = 'DAILY_LIMIT_EXCEEDED',
    QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',

    // 403
    FORBIDDEN = 'FORBIDDEN',

    // 404
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_BRAND_NOT_FOUND = 'USER_BRAND_NOT_FOUND',
    BACKGROUND_NOT_FOUND = 'BACKGROUND_NOT_FOUND',
    CUSTOMER_SUPPORT_NOT_FOUND = 'CUSTOMER_SUPPORT_NOT_FOUND',
    SEGMENT_NOT_FOUND = 'SEGMENT_NOT_FOUND',
    NOT_FOUND = 'NOT_FOUND',

    BRAND_SPOTLIGHT_MAXED = 'BRAND_SPOTLIGHT_MAXED',

    // 405
    METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
    HTTP_METHOD_NOT_ALLOWED = 'HTTP_METHOD_NOT_ALLOWED',

    // 408
    REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',

    // 409
    CONFLICT = 'CONFLICT',
    DUPLICATE = 'DUPLICATE',
    AUTH_EMAIL_EXISTED = 'AUTH_EMAIL_EXISTED',
    SEGMENT_NAME_EXISTED = 'SEGMENT_NAME_EXISTED',

    // 429
    RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
    USER_RATE_LIMIT_EXCEEDED = 'USER_RATE_LIMIT_EXCEEDED',
    TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

    // 500
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

    // 501
    NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
    UNSUPPORTED_METHOD = 'UNSUPPORTED_METHOD',

    // 503
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
    BACKEND_ERROR = 'BACKEND_ERROR',
    NOT_READY = 'NOT_READY',
    AUTH_INVALID_OTP = 'AUTH_INVALID_OTP',
    AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',

    SUBSCRIPTION_INVALID_PURCHASE_INFO = 'SUBSCRIPTION_INVALID_PURCHASE_INFO'
}
