export enum SuccessCode {
    // [!] USER
    USER_CREATED = 'USER_CREATED',
    USER_UPDATED = 'USER_UPDATED',
    USER_DELETED = 'USER_DELETED',

    // [!] USER SEGMENTS
    SEGMENT_CREATED = 'SEGMENT_CREATED',
    SEGMENT_UPDATED = 'SEGMENT_UPDATED',
    SEGMENT_DELETED = 'SEGMENT_DELETED',
    SUBSCRIPTION_SUCCESS = 'SUBSCRIPTION_SUCCESS',
    SEGMENT_NAME_VALID = 'SEGMENT_NAME_VALID',

    // [!] USER SETTINGS
    EMAIL_VALID = 'EMAIL_VALID',
    PASSWORD_CHANGED = 'PASSWORD_CHANGED',
    PASSWORD_UPDATED = 'PASSWORD_UPDATED',

    // [!] BRAND
    URL_VALID = 'URL_VALID',
    ONBOARDING_SKIPPED = 'ONBOARDING_SKIPPED',
    TUTORIAL_FINISHED = 'TUTORIAL_FINISHED',

    BRAND_CREATED = 'BRAND_CREATED',
    BRAND_UPDATED = 'BRAND_UPDATED',

    BRAND_ANALYTIC_UPDATED = 'BRAND_ANALYTIC_UPDATED',

    // [!] SPOTLIGHT
    BRAND_PINNED_TO_SPOTLIGHT = 'BRAND_PINNED_TO_SPOTLIGHT',
    BRAND_UNPINNED_FROM_SPOTLIGHT = 'BRAND_UNPINNED_FROM_SPOTLIGHT',

    // [!] WIDGETS
    WIDGET_CREATED = 'WIDGET_CREATED',
    WIDGET_UPDATED = 'WIDGET_UPDATED',
    WIDGET_DELETED = 'WIDGET_DELETED',

    WIDGET_VISIBILITY_CHANGED = 'WIDGET_VISIBILITY_CHANGED',
    WIDGET_ORDER_CHANGED = 'WIDGET_ORDER_CHANGED',

    // [!] WIDGET DESCRIPTION ITEMS
    WIDGET_DESCRIPTION_UPVOTE = 'WIDGET_DESCRIPTION_UPVOTE',
    WIDGET_DESCRIPTION_DOWNVOTE = 'WIDGET_DESCRIPTION_DOWNVOTE',

    // [!] WIDGETS TIP ITEMS
    WIDGET_TIPS_CREATED = 'WIDGET_TIPS_CREATED',
    WIDGET_TIPS_UPDATED = 'WIDGET_TIPS_UPDATED',
    WIDGET_TIPS_DELETED = 'WIDGET_TIPS_DELETED',

    // [!] BRAND REPORTS
    BRAND_REPORT_CREATED = 'BRAND_REPORT_CREATED',
    BRAND_REPORT_UPDATED = 'BRAND_REPORT_UPDATED',
    BRAND_REPORT_DELETED = 'BRAND_REPORT_DELETED',
    BRAND_REPORT_SOLVED = 'BRAND_REPORT_SOLVED',

    // [!] TEMPLATES
    TEMPLATE_CREATED = 'TEMPLATE_CREATED',
    TEMPLATE_UPDATED = 'TEMPLATE_UPDATED',
    TEMPLATE_DELETED = 'TEMPLATE_DELETED',
    TEMPLATE_CLONED = 'TEMPLATE_CLONED',

    // [!] VISITOR LOGS
    VISITOR_LOG_RECORDED = 'VISITOR_LOG_RECORDED',

    // [!] OTHERS
    POLLING_BOOTH_VOTED = 'POLLING_BOOTH_VOTED',

    // [!] BACKGROUNDS
    BACKGROUND_CREATED = 'BACKGROUND_CREATED',
    BACKGROUND_UPDATED = 'BACKGROUND_UPDATED',
    BACKGROUND_DELETED = 'BACKGROUND_DELETED',
    BACKGROUND_POSITION_CHANGED = 'BACKGROUND_POSITION_CHANGED',
    DEFAULT_BACKGROUND_SYNCED = 'DEFAULT_BACKGROUND_SYNCED',

    // [!] CUSTOMER SUPPORTS
    CUSTOMER_SUPPORT_CREATED = 'CUSTOMER_SUPPORT_CREATED',
    CUSTOMER_SUPPORT_UPDATED = 'CUSTOMER_SUPPORT_UPDATED'
}
